import type { Lesson } from "@/content/types";

export const yourDigitalFootprint: Lesson = {
  slug: "your-digital-footprint",
  title: "Your Digital Footprint",
  estimatedMinutes: 8,
  objective: "Understand what a digital footprint is and why it tends to last longer than expected.",
  blocks: [
    {
      type: "text",
      body: "Everything you post, comment, or share online contributes to a pattern that others — friends, strangers, future employers, colleges — can piece together over time. That pattern is your digital footprint, and it tends to outlast the moment you posted something, sometimes by years.",
    },
    {
      type: "vocabulary",
      term: {
        term: "Digital footprint",
        simpleDefinition:
          "The overall trail of information about you that exists online, built up from everything you've posted, shared, or been tagged in.",
        technicalDefinition:
          "The cumulative trace of data generated by a person's online activity, including both actively shared content and passively collected data (site visits, metadata). Deleting an individual post doesn't necessarily erase copies that were saved, cached, or shared elsewhere before deletion.",
      },
    },
    {
      type: "scenario",
      setup:
        "You post something in the heat of the moment that you regret an hour later, and delete it right away. A friend mentions that a couple of people had already taken screenshots before you deleted it.",
      choices: [
        {
          id: "assume-its-gone",
          text: "Don't worry about it — you deleted it, so it's gone.",
          isSafe: false,
          feedback:
            "Deletion removes it from the platform going forward, but it doesn't recall copies that already exist elsewhere — screenshots, in this case. This is exactly why the pause-before-posting habit matters more than the delete button.",
        },
        {
          id: "learn-the-lesson",
          text: "Accept that it may already exist beyond your control, and treat it as a reminder to pause before posting in the future.",
          isSafe: true,
          feedback:
            "That's the realistic and useful takeaway. It's not about never making mistakes online — it's about recognizing that \"delete\" isn't the same as \"undo.\"",
        },
      ],
    },
    {
      type: "text",
      body: "None of this means you should stop posting or sharing things you care about — it means treating a public or semi-public post the way you'd treat something said in a fairly public place: something you're comfortable standing behind later, not something you're counting on disappearing.",
    },
    {
      type: "question",
      prompt: "Why isn't deleting a post the same as fully removing it from existence?",
      options: [
        { id: "a", text: "Because copies may already exist elsewhere — screenshots, shares, caches — that deletion doesn't reach" },
        { id: "b", text: "Deleting a post does completely erase every copy of it everywhere" },
      ],
      correctOptionId: "a",
      explanation:
        "Deletion controls what the platform shows going forward, not what already left your control before you deleted it.",
    },
  ],
  quiz: {
    slug: "module-08-social-media-safety-review",
    questions: [
      {
        type: "question",
        prompt: "Why does geotagging deserve specific caution beyond general oversharing?",
        options: [
          { id: "a", text: "Precise location, especially with timing, is a specific and concrete disclosure" },
          { id: "b", text: "It has no real privacy implications" },
        ],
        correctOptionId: "a",
        explanation: "Exact location data combined with timing (like being away from home) is more specific and actionable than a vague mention.",
      },
      {
        type: "question",
        prompt: "Someone unfamiliar pushes to quickly move your conversation to a different app. What should that suggest?",
        options: [
          { id: "a", text: "It's a common move-away-from-safety-tools pattern worth being cautious about" },
          { id: "b", text: "It's a normal, unremarkable preference" },
        ],
        correctOptionId: "a",
        explanation: "This pressure shows up across multiple kinds of scams and is worth treating as a signal, not a coincidence.",
      },
      {
        type: "question",
        prompt: "A friend's account sends an odd, link-heavy message. What's the safest response?",
        options: [
          { id: "a", text: "Click it, since you already trust that account" },
          { id: "b", text: "Verify with your friend through a different channel first" },
        ],
        correctOptionId: "b",
        explanation: "A familiar account doesn't guarantee the person controlling it right now is actually your friend.",
      },
      {
        type: "question",
        prompt: "Why doesn't deleting a post fully undo having shared it?",
        options: [
          { id: "a", text: "Copies (screenshots, shares) may already exist beyond the platform's control" },
          { id: "b", text: "Deletion is always fully complete and permanent everywhere" },
        ],
        correctOptionId: "a",
        explanation: "\"Delete\" removes it going forward — it can't reach copies that already left your control.",
      },
    ],
  },
};
